name: Koyeb Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Koyeb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: docker build -t advshop-app .

      - name: Log in to Koyeb and Redeploy
        env:
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}
        run: |
          curl -X POST "https://app.koyeb.com/v1/services/bd707a90-bf5b-42b1-b0fa-94f1a0e81e44/redeploy" \
               -H "Authorization: Bearer $KOYEB_API_TOKEN"
